AgreementSign/Models/AgreementEditViewModel.cs
using System.Web.Mvc;

namespace AgreementSign.Models
{
    public class AgreementEditViewModel
    {
        [AllowHtml]
        public string Text { get; set; }
    }
}

AgreementSign/Models/AgreementSignViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using ExpressiveAnnotations.Attributes;

namespace AgreementSign.Models
{
    public class AgreementSignViewModel
    {
        [AllowHtml]
        public string Text { get; set; }

        [Required]
        [Display(Name = "Print Full Name")]
        public string FullName { get; set; }

        [RequiredIf("SignType == 0")]
        [UIHint("SignaturePad")]
        public byte[] Signature { get; set; }

        public SignType SignType { get; set; }

        [RequiredIf("SignType == 1")]
        public string UseKeyboardInput { get; set; }
    }
}

AgreementSign/Models/AgreementViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace AgreementSign.Models
{
    public class AgreementViewModel
    {
        [AllowHtml]
        public string Text { get; set; }

        public List<SignViewModel> Signs { get; set; }
    }
}

AgreementSign/Models/SignType.cs
namespace AgreementSign.Models
{
    public enum SignType
    {
        ManualSign = 0,
        GeneratedSign = 1
    }
}

AgreementSign/Models/SignViewModel.cs
using System;
using AgreementSign.DAL.Model;

namespace AgreementSign.Models
{
    public class SignViewModel
    {
        public SignViewModel(Sign sign)
        {
            Id = sign.Id;
            FullName = sign.FullName;
            CreatedDate = sign.CreatedDate;
            Signature = sign.Signature;
        }

        public long Id { get; set; }

        public string FullName { get; set; }

        public DateTime? CreatedDate { get; set; }

        public byte[] Signature { get; set; }
    }
}

AgreementSign/Controllers/AgreementController.cs
using System;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AgreementSign.DAL.Model;
using AgreementSign.DAL.Repositories;
using AgreementSign.Helpers;
using AgreementSign.Models;

namespace AgreementSign.Controllers
{
    public class AgreementController : Controller
    {
        private IAgreementRepository AgreementRepository { get; }

        private ISignRepository SignRepository { get; }

        public AgreementController(IAgreementRepository agreementRepository, ISignRepository signRepository)
        {
            AgreementRepository = agreementRepository;
            SignRepository = signRepository;
        }

        public ActionResult Index()
        {
            var agreement = AgreementRepository.FirstOrDefault();
            var signs = SignRepository.GetAll();
            var useDefualtText = Boolean.Parse(ConfigurationManager.AppSettings["UseDefaultText"]);

            return View(new AgreementViewModel
            {
                Text = agreement?.Text ?? (useDefualtText ? Resources.Agreement.Text : string.Empty),
                Signs = signs.Select(x => new SignViewModel(x)).ToList()
            });
        }

        [HttpPost]
        public ActionResult Sign(AgreementSignViewModel model)
        {
            if (ModelState.IsValid)
            {
                SignRepository.Upsert(new Sign
                {
                    FullName = model.FullName,
                    CreatedDate = DateTime.UtcNow,
                    Signature = model.SignType == SignType.ManualSign? model.Signature : Utils.ImageToByteArray(Utils.ConvertTextToImage(model.UseKeyboardInput.Trim()))
                });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(AgreementEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var agreement = AgreementRepository.FirstOrDefault() ?? new Agreement();
                agreement.Text = model.Text;
                AgreementRepository.Upsert(agreement);
            }

            return RedirectToAction("Index");
        }
    }
}

AgreementSign/Views/Agreement/Index.cshtml
@using AgreementSign.Helpers
@using AgreementSign.Models
@model AgreementViewModel

@{
    ViewBag.Title = "Agreement Sign Page";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sign Agreement <a data-toggle="modal" href="#editModal" class="pull-right"><i class="fa fa-edit"></i></a></h3>
            </div>
            <div class="panel-body">
                @Html.Partial("_SignForm", new AgreementSignViewModel { Text = Model.Text })
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editTitle">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="editTitle">Edit Agreement</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("_EditForm", new AgreementEditViewModel { Text = Model.Text })
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="edit" type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(function() {

            $(document).ready(function() {
                var checked = $('#sign-form input[name="SignType"]:radio:checked');
                if (checked.val() === '@SignType.ManualSign.ToString()') {
                    $('#sign-form .signature-pad ').show();
                    $('#sign-form input[name="UseKeyboardInput"]').hide();
                } else {
                    $('#sign-form .signature-pad').hide();
                    $('#sign-form input[name="UseKeyboardInput"]').show();
                }

                var sp = getSignaturePad('#sign-form .signature-pad');
                if (sp.isEmpty()) {
                    $('#sign-form button[type="submit"]').prop('disabled', true);
                } else {
                    $('#sign-form button[type="submit"]').prop('disabled', false);
                }
            });

            $('#edit').click(function(e) {
                e.preventDefault();
                $('#editModal form').trigger('submit');
            });

            $('#editor').trumbowyg();

            $('#sign-form input[name="SignType"]:radio').change(function() {
                var checked = $('#sign-form input[name="SignType"]:radio:checked');
                if (checked.val() === '@SignType.ManualSign.ToString()') {
                    $('#sign-form .signature-pad').show();
                    $('#sign-form input[name="UseKeyboardInput"]').hide();
                    var sp = getSignaturePad('#sign-form .signature-pad');
                    if (sp.isEmpty()) {
                        $('#sign-form button[type="submit"]').prop('disabled', true);
                    } else {
                        $('#sign-form button[type="submit"]').prop('disabled', false);
                    }
                } else {
                    $('#sign-form .signature-pad').hide();
                    $('#sign-form input[name="UseKeyboardInput"]').show();
                    if (!$('#sign-form input[name="UseKeyboardInput"]').val()) {
                        $('#sign-form button[type="submit"]').prop('disabled', true);
                    } else {
                        $('#sign-form button[type="submit"]').prop('disabled', false);
                    }
                }
            });

            $('#sign-form input[name="UseKeyboardInput"]').on('input', function() {
                if (!$(this).val()) {
                    $('#sign-form button[type="submit"]').prop('disabled', true);
                } else {
                    $('#sign-form button[type="submit"]').prop('disabled', false);
                }
            });

            $('#sign-form .signature-pad .btn-clear-canvas').on('click', function() {
                $('#sign-form button[type="submit"]').prop('disabled', true);
            });

            $('#sign-form .signature-pad input[type="hidden"]').on('change', function () {
                var sp = getSignaturePad('#sign-form .signature-pad');
                if (sp.isEmpty()) {
                    $('#sign-form button[type="submit"]').prop('disabled', true);
                } else {
                    $('#sign-form button[type="submit"]').prop('disabled', false);
                }
            });
        });

    </script>
    <script src="~/Scripts/signature_pad.min.js"></script>
    <script src="~/Scripts/SignaturePadInit.js"></script>
}

AgreementSign/Views/Agreement/_EditForm.cshtml
@model AgreementSign.Models.AgreementEditViewModel

@using (Html.BeginForm("Edit", "Agreement", FormMethod.Post))
{
    <div class="form-group">
        @Html.TextAreaFor(x => x.Text, new { id ="editor"})
    </div>
}

AgreementSign/Views/Agreement/_SignForm.cshtml
@using AgreementSign.Models
@model AgreementSignViewModel

@using (Html.BeginForm("Sign", "Agreement", null, FormMethod.Post, new { id = "sign-form"}))
{
    <div class="form-group mt-25">
        @Html.HiddenFor(x => x.Text)
        @Html.Raw(Model.Text)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.FullName, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.FullName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.FullName, null, new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label class="radio-inline">@Html.RadioButtonFor(x => x.SignType, SignType.ManualSign) Sign Here Using Mouse or Finger/Stylus</label>
        <label class="radio-inline">@Html.RadioButtonFor(x => x.SignType, SignType.GeneratedSign) Use Keyboard</label>        
    </div>
    @Html.EditorFor(x => x.Signature)
    <div class="form-group">
        @Html.TextBoxFor(x => x.UseKeyboardInput, new { @class = "form-control input-lg"})
        @Html.ValidationMessageFor(x => x.UseKeyboardInput, null, new { @class = "text-danger" })
    </div>
    <div class="form-group text-center">
        <button type="submit" class="btn btn-lg btn-success">Submit</button>
    </div>
}

AgreementSign/Views/Shared/DisplayTemplates/SignaturePad.cshtml
@model byte[]

<div class="signature-pad">
    <canvas class="panel panel-default"></canvas>
    @Html.HiddenFor(model => model, new { @disabled = "disabled" })
</div>

AgreementSign/Views/Shared/EditorTemplates/SignaturePad.cshtml
@model byte[]

<div class="signature-pad" signature-pad-id="@Guid.NewGuid()">
    <canvas class="panel panel-default"></canvas>
    <button type="button" class="btn btn-default btn-sm btn-clear-canvas">Clear</button>
    @Html.HiddenFor(model => model, ViewData["htmlAttributes"])
</div>

AgreementSign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Agreement Sign Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Agreement", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sign", "Index", "Agreement")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br/>
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - Agreement Sign Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/trumbowyg")
    @Scripts.Render("~/bundles/jqueryval")
    
    @RenderSection("scripts", required: false)
</body>
</html>